# Generated by Django 4.2.13 on 2024-07-10 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proTel', models.CharField(max_length=20)),
                ('proEmergencyContactName', models.CharField(max_length=50)),
                ('proEmergencyContactTel', models.CharField(max_length=20)),
                ('proBirthDate', models.DateField(blank=True, null=True)),
                ('proAlerg', models.CharField(help_text='Ingrese NO si no tiene alergias', max_length=50)),
                ('proEnfer', models.CharField(help_text='Ingrese NO si no tiene enfermedades', max_length=50)),
                ('proMedi', models.CharField(help_text='Ingrese NO si no toma medicación', max_length=50)),
                ('proRefe', models.CharField(help_text='Recomendación, Red Social, etc', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serName', models.CharField(help_text='Ingrese el nombre del sero de Servicio', max_length=50)),
                ('serDesc', models.TextField(help_text='Breve descripcion del Servicio por hacer', max_length=500)),
                ('serTime', models.TimeField(blank=True, help_text='Formato: 09:15:00  Tiempo que le toma en promedio en realizar el Servicio.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turDate', models.DateField()),
                ('turHrFrom', models.TimeField()),
                ('turHrTo', models.TimeField()),
                ('turSenia', models.FloatField(blank=True, default=0, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.profile')),
                ('serviceType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comContent', models.TextField(blank=True, max_length=500, null=True)),
                ('comDateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.profile')),
            ],
            options={
                'ordering': ['comDateTime'],
            },
        ),
    ]
