# Generated by Django 4.2.13 on 2024-08-10 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comIsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='proIsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='serIsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='turIsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proAlerg',
            field=models.CharField(help_text='Ingrese NO si no tiene alergias', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proEnfer',
            field=models.CharField(help_text='Ingrese NO si no tiene enfermedades', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proMedi',
            field=models.CharField(help_text='Ingrese NO si no toma medicación', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proRefe',
            field=models.CharField(help_text='Recomendación, Red Social, etc', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
