# Generated by Django 4.2.13 on 2024-08-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_comment_comisactive_profile_proisactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comIsActive',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='proIsActive',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='serIsActive',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='turIsActive',
            new_name='isActive',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='turSenia',
        ),
    ]
