# Generated by Django 4.2.13 on 2024-08-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_comisactive_comment_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='turHrTo',
        ),
    ]
